import { randomBytes } from 'node:crypto';
import { existsSync, lstatSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import bcrypt from 'bcryptjs';

const projectRoot = path.resolve(new URL('..', import.meta.url).pathname);
const envPath = path.join(projectRoot, '.env');
const credentialsDir = process.env.GEV_CREDENTIALS_DIR || '/root/.secrets';
const credentialsPath = path.join(credentialsDir, 'godseyeview-initial-credentials.txt');
const force = process.argv.includes('--force');
const ensureSession = process.argv.includes('--ensure-session');
const usernames = process.argv.slice(2).filter((value) => !['--force', '--ensure-session'].includes(value));

function upsertEnvLine(envText, key, value) {
  const line = `${key}=${value}`;
  const expression = new RegExp(`^${key}=.*$`, 'm');
  return expression.test(envText)
    ? envText.replace(expression, line)
    : `${envText.trimEnd()}\n${line}\n`;
}

function hasStrongSessionSecret(envText) {
  const raw = envText.match(/^GEV_SESSION_SECRET=(.*)$/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '') || '';
  try {
    return Buffer.from(raw, 'base64url').length >= 32;
  } catch {
    return false;
  }
}

if (ensureSession) {
  if (usernames.length || force) {
    console.error('Usage: node scripts/provision-auth.mjs --ensure-session');
    process.exit(2);
  }
  if (!existsSync(envPath)) {
    console.error(`Cannot add a session secret because ${envPath} does not exist.`);
    process.exit(1);
  }
  if (lstatSync(envPath).isSymbolicLink()) {
    console.error(`Refusing to overwrite symbolic link: ${envPath}`);
    process.exit(1);
  }
  let envText = await readFile(envPath, 'utf8');
  let changed = false;
  if (!/^GEV_AUTH_USERS=/m.test(envText) && /^GEV_BASIC_AUTH_USERS=/m.test(envText)) {
    envText = envText.replace(/^GEV_BASIC_AUTH_USERS=/m, 'GEV_AUTH_USERS=');
    changed = true;
  }
  if (!hasStrongSessionSecret(envText)) {
    envText = upsertEnvLine(envText, 'GEV_SESSION_SECRET', randomBytes(48).toString('base64url'));
    changed = true;
  }
  if (changed) await writeFile(envPath, envText, { mode: 0o600 });
  console.log(`Application authentication configuration is ready in ${envPath}.`);
  process.exit(0);
}

if (usernames.length !== 2) {
  console.error('Usage: node scripts/provision-auth.mjs <user-1> <user-2> [--force]\n'
    + '       node scripts/provision-auth.mjs --ensure-session');
  process.exit(2);
}

for (const username of usernames) {
  if (!/^[A-Za-z0-9._-]{1,32}$/.test(username)) {
    console.error(`Invalid username: ${username}`);
    process.exit(2);
  }
}

if (new Set(usernames).size !== 2) {
  console.error('The two usernames must be different.');
  process.exit(2);
}

if (!force && (existsSync(envPath) || existsSync(credentialsPath))) {
  console.error('Authentication is already provisioned; pass --force to rotate both accounts.');
  process.exit(1);
}

for (const target of [envPath, credentialsPath]) {
  if (existsSync(target) && lstatSync(target).isSymbolicLink()) {
    console.error(`Refusing to overwrite symbolic link: ${target}`);
    process.exit(1);
  }
}

const accounts = await Promise.all(usernames.map(async (username) => {
  const password = randomBytes(24).toString('base64url');
  const hash = await bcrypt.hash(password, 12);
  return { username, password, hash };
}));

const initialEnv = `# Generated by scripts/provision-auth.mjs. Keep mode 0600.
GEV_HOSTNAME=godseyeview.jimtrebes.fr
GEV_AUTH_USERS=
GEV_SESSION_SECRET=
HOST=0.0.0.0
PORT=4173
GEV_ALLOWED_HOSTS=godseyeview.jimtrebes.fr,localhost,127.0.0.1
VITE_CACHE_DIR=/tmp/vite-cache
GEV_RATELIMIT_OPENAI_PER_MIN=10
GEV_RATELIMIT_GOOGLE_PER_MIN=20
OPENSKY_AUTH_MODE=anon
GOOGLE_MAPS_API_KEY=
CESIUM_ION_TOKEN=
OPENAI_API_KEY=
AISSTREAM_API_KEY=
FIRMS_MAP_KEY=
TOMTOM_API_KEY=
OPENSKY_CLIENT_ID=
OPENSKY_CLIENT_SECRET=
LAUNCH_LIBRARY_TOKEN=
`;

let envText = existsSync(envPath) ? await readFile(envPath, 'utf8') : initialEnv;
const authValue = accounts.map(({ username, hash }) => `${username}:${hash}`).join(',');
const authLine = `GEV_AUTH_USERS='${authValue}'`;
if (/^GEV_AUTH_USERS=.*$/m.test(envText)) {
  envText = envText.replace(/^GEV_AUTH_USERS=.*$/m, authLine);
} else if (/^GEV_BASIC_AUTH_USERS=.*$/m.test(envText)) {
  envText = envText.replace(/^GEV_BASIC_AUTH_USERS=.*$/m, authLine);
} else {
  envText = `${envText.trimEnd()}\n${authLine}\n`;
}
if (!hasStrongSessionSecret(envText)) {
  envText = upsertEnvLine(envText, 'GEV_SESSION_SECRET', randomBytes(48).toString('base64url'));
}

await writeFile(envPath, envText, { mode: 0o600 });
await mkdir(credentialsDir, { recursive: true, mode: 0o700 });

const credentialText = [
  "God's Eye View — initial credentials",
  'URL: https://godseyeview.jimtrebes.fr',
  `Generated: ${new Date().toISOString()}`,
  '',
  ...accounts.flatMap(({ username, password }, index) => [
    `Account ${index + 1}`,
    `username: ${username}`,
    `password: ${password}`,
    '',
  ]),
  'Store these passwords in a password manager, then remove this plaintext file.',
  'Rotate both accounts with: npm run provision:auth -- <user-1> <user-2> --force',
  '',
].join('\n');

await writeFile(credentialsPath, credentialText, { mode: 0o600 });
await writeFile(path.join(projectRoot, '.auth-provisioned'), `${new Date().toISOString()}\n`, { mode: 0o600 });

console.log(`Provisioned exactly two accounts: ${usernames.join(', ')}`);
console.log(`Runtime hashes and session configuration: ${envPath}`);
console.log(`One-time plaintext credentials: ${credentialsPath}`);
